version: '3'
services:
  ts_discord_notify_ssh:
    build:
      context: .
      dockerfile: Dockerfile
    # set DISCORD_WEBHOOK_URL in .env file
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - ${PWD}/../tsrecorder:/data
    restart: unless-stopped
